import json
from pathlib import Path
import subprocess
import sys
import joblib

from rta_pipeline import SMOTENCFrame
import pandas as pd
import streamlit as st
from sklearn.metrics import (
    accuracy_score, confusion_matrix, f1_score,
    matthews_corrcoef, precision_score, recall_score,
    roc_auc_score, classification_report
)

BASE = Path(__file__).resolve().parent

st.set_page_config(
    page_title="Road Accident Severity Predictor",
    page_icon="🚗",
    layout="wide",
)

st.title("🚗 Road Accident Severity Prediction")
st.caption("Machine-learning classification using five trained models")

MODEL_FILES = {
    "Logistic Regression": "logistic_regression.pkl",
    "Decision Tree": "decision_tree.pkl",
    "KNN": "knn.pkl",
    "Gaussian Naive Bayes": "gaussian_naive_bayes.pkl",
    "Random Forest": "random_forest.pkl",
}
req_artifacts = [
    BASE / "label_encoder.pkl",
    BASE / "fitted_pipelines.pkl",
    *[BASE / "model" / filename for filename in MODEL_FILES.values()],
]

def ensure_training_artifacts():
    missing_files = [path for path in req_artifacts if not path.exists()]
    if not missing_files:
        return

    st.warning("Required model artifacts are missing. Training them now so the app can continue. This may take a minute or two.")

    train_script = BASE / "train_models.py"
    if not train_script.exists():
        st.error("The training script is missing, so the app cannot rebuild the model artifacts.")
        st.stop()

    try:
        subprocess.run([sys.executable, str(train_script)],cwd=str(BASE),check=True)
    except subprocess.CalledProcessError as exc:
        st.error(f"Model training failed with exit code {exc.returncode}.")
        st.stop()

    remaining_missing = [path for path in req_artifacts if not path.exists()]
    if remaining_missing:
        st.error("Training finished but some required artifacts are still missing:")
        st.write(remaining_missing)
        st.stop()


ensure_training_artifacts()

@st.cache_resource
def load_artifacts():
    if (BASE / "fitted_pipelines.pkl").exists():
        pipelines = joblib.load(BASE / "fitted_pipelines.pkl")
    else:
        pipelines = {
            name: joblib.load(BASE / "model" / filename)
            for name, filename in MODEL_FILES.items()
        }
    encoder = joblib.load(BASE / "label_encoder.pkl")
    with open(BASE / "feature_metadata.json", "r", encoding="utf-8") as f:
        metadata = json.load(f)
    return pipelines, encoder, metadata

try:
    pipelines, label_encoder, metadata = load_artifacts()
except FileNotFoundError:
    st.error(
        "Saved model files are missing. Run train_models.py first, "
        "then refresh the app."
    )
    st.stop()

st.sidebar.header("Model Selection")
model_name = st.sidebar.selectbox(
    "Choose a classification model",
    list(MODEL_FILES.keys()),
)
st.sidebar.subheader("Evaluation dataset")
test_data_path = BASE / "test_data.csv"
if test_data_path.exists():
    with open(test_data_path, "rb") as f:
        test_data_bytes = f.read()
    st.sidebar.download_button(
        label="Download test_data.csv",
        data=test_data_bytes,
        file_name="test_data.csv",
        mime="text/csv",
        help="Download the evaluation dataset generated for model testing.",
    )
else:
    st.sidebar.warning("No test_data.csv found yet. Training will generate it automatically.")
    
uploaded = st.file_uploader(
    "Upload test_data.csv",
    type=["csv"],
    help="Use the test_data.csv generated by train_models.py.",
)

if uploaded is None:
    st.info("Upload the generated test_data.csv to evaluate a model, or download it from the sidebar if it is already available.")
    st.markdown(
        """
        **Required workflow**
        1. Run `train_models.py`.
        2. Upload the generated `test_data.csv`.
        3. Select a model from the sidebar.
        4. Review the six evaluation metrics and confusion matrix.
        """
    )
    st.stop()

data = pd.read_csv(uploaded)
target = metadata["target"]

if target not in data.columns:
    st.error(f"The uploaded CSV must contain the target column: `{target}`")
    st.stop()

X = data.drop(columns=[target])
y_text = data[target].astype(str)

# Match the training pipeline's feature order.
expected_features = (
    metadata["ordinal_cols"]
    + metadata["nominal_cols"]
    + metadata["numeric_cols"]
)

missing_features = [c for c in expected_features if c not in X.columns]
if missing_features:
    st.error("Missing required feature columns:")
    st.write(missing_features)
    st.stop()

X = X[expected_features]

try:
    y_true = label_encoder.transform(y_text)
except ValueError as exc:
    st.error(f"Target labels do not match the training classes: {exc}")
    st.stop()

pipeline = pipelines[model_name]
y_pred = pipeline.predict(X)
y_proba = pipeline.predict_proba(X)

accuracy = accuracy_score(y_true, y_pred)
auc = roc_auc_score(
    y_true, y_proba, multi_class="ovr", average="macro"
)
precision = precision_score(
    y_true, y_pred, average="macro", zero_division=0
)
recall = recall_score(
    y_true, y_pred, average="macro", zero_division=0
)
f1 = f1_score(
    y_true, y_pred, average="macro", zero_division=0
)
mcc = matthews_corrcoef(y_true, y_pred)

st.subheader(f"Evaluation: {model_name}")

c1, c2, c3 = st.columns(3)
c4, c5, c6 = st.columns(3)

c1.metric("Accuracy", f"{accuracy:.4f}")
c2.metric("AUC (macro OvR)", f"{auc:.4f}")
c3.metric("Precision (macro)", f"{precision:.4f}")
c4.metric("Recall (macro)", f"{recall:.4f}")
c5.metric("F1 (macro)", f"{f1:.4f}")
c6.metric("MCC", f"{mcc:.4f}")

st.subheader("Confusion Matrix")
cm = confusion_matrix(y_true, y_pred)
cm_df = pd.DataFrame(
    cm,
    index=label_encoder.classes_,
    columns=label_encoder.classes_,
)
st.dataframe(cm_df, use_container_width=True)

st.subheader("Classification Report")
report = classification_report(
    y_true,
    y_pred,
    target_names=label_encoder.classes_,
    output_dict=True,
    zero_division=0,
)
st.dataframe(
    pd.DataFrame(report).T.round(4),
    use_container_width=True,
)

st.subheader("Prediction Preview")
preview = X.copy()
preview["Actual Severity"] = y_text.values
preview["Predicted Severity"] = label_encoder.inverse_transform(y_pred)
st.dataframe(preview.head(20), use_container_width=True)
